import HashMap from './HashMap.js';

const newHashMap = new HashMap();
console.log(newHashMap);
newHashMap.set('dog', 'eats cats');
newHashMap.set('cat', 'eats fish');
console.log(newHashMap.loadFactor());
console.log(newHashMap.buckets);
newHashMap.set('cat', 'eats crabs');
newHashMap.set('crab', 'eats fish');
newHashMap.set('bee', 'eats flowers');
newHashMap.set('cow', 'eats flowers');
console.log(newHashMap.loadFactor());
console.log(newHashMap.buckets);
newHashMap.set('dragonfly', 'eats fish');
newHashMap.set('bull', 'eats flowers');
newHashMap.set('chicken', 'eats flowers');
console.log(newHashMap.loadFactor());
console.log(newHashMap.buckets);
newHashMap.set('fox', 'eats fish');
newHashMap.set('pig', 'eats flowers');
newHashMap.set('tucan', 'eats flowers');
console.log(newHashMap.loadFactor());
console.log(newHashMap.buckets);
newHashMap.set('lamb', 'eats fish');
newHashMap.set('goat', 'eats flowers');
newHashMap.set('monkey', 'eats flowers');
console.log(newHashMap.loadFactor());
console.log(newHashMap.buckets);
